### ISSUE TITLE
fingerprint reader not detected

### ISSUE THREAD

**Issue by auroraanna** [crdroidandroid/android_device_xiaomi_ginkgo#11]
Previously I was able to unlock my phone using it's fingerprint reader on the crdroid rom. I haven't changed any security settings or disconnected the fingerprint reader but when I turn on the screen of my phone it says "Fingerprint hardware not available". This bug correlates with when I installed the crdroid update from 6th of April.

**Comment by DarkJoker360** [comment]
Will be fixed in newer builds: https://github.com/crdroidandroid/android_device_xiaomi_ginkgo/commit/9ab10f6ecc84e5bd33f7067022ee31f2aa021071
